---

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:

- name: repo
  type: git
  source:
    uri: ((app-url))
    branch: ((app-branch))
    private_key: ((github-private-key))

- name: tools
  type: git
  source:
    uri: ((tools-scripts-url))
    branch: ((tools-branch))

- name: cf-test
  type: cf
  source:
    api: ((cf-api))
    username: ((cf-username))
    password: ((cf-password))
    organization: ((cf-org))
    space: test
    skip_cert_check: true

- name: cf-stage
  type: cf
  source:
    api: ((cf-api))
    username: ((cf-username))
    password: ((cf-password))
    organization: ((cf-org))
    space: stage
    skip_cert_check: true

- name: cf-prod
  type: cf
  source:
    api: ((cf-api))
    username: ((cf-username))
    password: ((cf-password))
    organization: ((cf-org))
    space: prod
    skip_cert_check: true

- name: pre-release
  type: github-release
  source:
    user: ((git-user))
    access_token: ((access-token))
    check: true
    repository: ((app-repository))
    include_source_tarball: true
    include_source_zip: true
    pre_release: true

- name: release
  type: github-release
  source:
    user: ((git-user))
    access_token: ((access-token))
    check: true
    repository: ((app-repository))
    include_source_tarball: true
    include_source_zip: true
    pre_release: false

- name: slack-alert
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/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


jobs:

- name: analyze-repo
  serial: true
  public: true # cf does not shows auth. logs so it is ok
  plan:
  - get: repo
    trigger: true
  - get: tools
  - task: build
    file: tools/scripts/analyze.yml

- name: analyze-pre-release
  serial: true
  public: true # cf does not shows auth. logs so it is ok
  plan:
  - get: repo
  - get: tools
  - get: pre-release
    trigger: true
  - task: build
    file: tools/scripts/analyze.yml

- name: analyze-release
  serial: true
  public: true # cf does not shows auth. logs so it is ok
  plan:
  - get: repo
  - get: tools
  - get: release
    trigger: true
  - task: build
    file: tools/scripts/analyze.yml

- name: tests-repo
  serial: true
  public: true # cf does not shows auth. logs so it is ok
  plan:
  - get: repo
    trigger: true
    passed: [ analyze-repo ]
  - get: tools
  - task: build
    file: tools/scripts/analyze.yml

- name: tests-pre-release
  serial: true
  public: true # cf does not shows auth. logs so it is ok
  plan:
  - get: repo
  - get: pre-release
    trigger: true
    passed: [ analyze-pre-release ]
  - get: tools
  - task: build
    file: tools/scripts/analyze.yml

- name: tests-release
  serial: true
  public: true # cf does not shows auth. logs so it is ok
  plan:
  - get: repo
  - get: release
    trigger: true
    passed: [ analyze-release ]
  - get: tools
  - task: build
    file: tools/scripts/analyze.yml

- name: deploy-to-test
  serial: true
  public: true # cf does not shows auth. logs so it is ok
  plan:
  - get: repo
    trigger: true
    passed: [ tests-repo ]
  - get: tools
  - task: build
    file: tools/scripts/build.yml
    params:
      <<: *common-params
  - put: cf-test
    params:
      manifest: build/manifest.yml
      current_app_name: ((app-name))
      path: build/app.jar
  - put: slack-alert
    params:
      channel: '#spring-paris-demo'
      text: |
        The build had a result. Check it out at:
        https://a-concourse2-630322659.eu-west-1.elb.amazonaws.com//builds/$BUILD_ID
        The application is now available in development at https://basic-concourse.development.cfapps.alex.examples.cf

- name: deploy-to-stage
  public: true
  serial: true
  plan:
  - get: repo
  - get: pre-release
    trigger: true
    passed: [ tests-pre-release  ]
    params:
      include_source_tarball: true
  - get: tools
  - task: build
    file: tools/scripts/build-pre-release.yml
    params:
      <<: *common-params
  - put: cf-stage
    params:
      manifest: build/manifest.yml
      current_app_name: ((app-name))
      path: build/app.jar
  - put: slack-alert
    params:
      channel: '#spring-paris-demo'
      text: |
        The build had a result. Check it out at:
        https://a-concourse2-630322659.eu-west-1.elb.amazonaws.com//builds/$BUILD_ID
        The application is now available in qa at https://basic-concourse.qa.cfapps.alex.examples.cf

- name: deploy-to-prod
  public: true
  serial: true
  plan:
  - get: repo
  - get: tools
  - get: release
    trigger: true
    passed: [ tests-release  ]
    params:
      include_source_tarball: true
  - task: build
    file: tools/scripts/build-release.yml
    params:
      <<: *common-params
  - put: cf-prod
    params:
      manifest: build/manifest.yml
      current_app_name: ((app-name))
      path: build/app.jar
  - put: slack-alert
    params:
      channel: '#spring-paris-demo'
      text: |
        The build had a result. Check it out at:
        https://a-concourse2-630322659.eu-west-1.elb.amazonaws.com//builds/$BUILD_ID
        The application is now available in production at https://basic-concourse.production.cfapps.alex.examples.cf


common-params: &common-params
  APP_NAME: ((app-name))
