---

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:

- name: repo
  type: git
  source:
    uri: ((app-url))
    branch: ((app-branch))
    private_key: ((github-private-key))

- name: tools
  type: git
  source:
    uri: ((tools-scripts-url))
    branch: ((tools-branch))

- name: cf-test
  type: cf
  source:
    api: ((cf-api))
    username: ((cf-username))
    password: ((cf-password))
    organization: ((cf-org))
    space: test
    skip_cert_check: true

- name: cf-stage
  type: cf
  source:
    api: ((cf-api))
    username: ((cf-username))
    password: ((cf-password))
    organization: ((cf-org))
    space: stage
    skip_cert_check: true

- name: cf-prod
  type: cf
  source:
    api: ((cf-api))
    username: ((cf-username))
    password: ((cf-password))
    organization: ((cf-org))
    space: prod
    skip_cert_check: true

- name: pre-release
  type: github-release
  source:
    user: ((git-user))
    access_token: ((git-access-token))
    check: true
    repository: ((app-repository))
    include_source_tarball: true
    include_source_zip: true
    pre_release: true

- name: release
  type: github-release
  source:
    user: ((git-user))
    access_token: ((git-access-token))
    check: true
    repository: ((app-repository))
    include_source_tarball: true
    include_source_zip: true
    pre_release: false

- name: slack-alert
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/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


jobs:

- name: analyze-source-code
  serial: true
  public: true # cf does not shows auth. logs so it is ok
  plan:
  - get: repo
    trigger: true
  - get: tools
  - task: build
    file: tools/scripts/analyze.yml

- name: integration-tests
  serial: true
  public: true # cf does not shows auth. logs so it is ok
  plan:
  - get: repo
    trigger: true
    passed: [ analyze-source-code ]
  - get: tools
  - task: build
    file: tools/scripts/analyze.yml

- name: end-to-end-tests
  serial: true
  public: true # cf does not shows auth. logs so it is ok
  plan:
  - get: pre-release
    trigger: true
  - get: tools
  - task: build
    file: tools/scripts/analyze.yml

- name: deploy-((app-name))-to-test
  serial: true
  public: true # cf does not shows auth. logs so it is ok
  plan:
  - get: repo
    trigger: true
    passed: [ integration-tests ]
  - get: tools
  - task: build
    file: tools/scripts/build.yml
    params:
      <<: *common-params
  - put: cf-test
    params:
      manifest: build/manifest.yml
      current_app_name: ((app-name))
      path: build/app.jar
  - put: slack-alert
    params:
      channel: '#spring-paris-demo'
      text: |
        ***************************************
        The build had a result. Check it out at:
        https://a-concourse2-630322659.eu-west-1.elb.amazonaws.com//builds/$BUILD_ID
        The application is now available in Test - $BUILD_JOB_NAME

- name: deploy-((app-name))-to-stage
  public: true
  serial: true
  plan:
  - get: pre-release
    trigger: true
    passed: [ end-to-end-tests  ]
    params:
      include_source_tarball: true
  - get: tools
  - task: build
    file: tools/scripts/build-pre-release.yml
    params:
      <<: *common-params
  - put: cf-stage
    params:
      manifest: build/manifest.yml
      current_app_name: ((app-name))
      path: build/app.jar
  - put: slack-alert
    params:
      channel: '#spring-paris-demo'
      text: |
        ***************************************
        The build had a result. Check it out at:
        https://a-concourse2-630322659.eu-west-1.elb.amazonaws.com//builds/$BUILD_ID
        The application is now available in Stage - $BUILD_JOB_NAME

- name: deploy-((app-name))-to-prod
  public: true
  serial: true
  plan:
  - get: tools
  - get: release
    trigger: true
    passed: [  create-metrics-forwarder-prod ]
    params:
      include_source_tarball: true
  - task: build
    file: tools/scripts/build-release.yml
    params:
      <<: *common-params
  - put: cf-prod
    params:
      manifest: build/manifest.yml
      current_app_name: ((app-name))
      path: build/app.jar
  - put: slack-alert
    params:
      channel: '#spring-paris-demo'
      text: |
        ***************************************
        The build had a result. Check it out at:
        https://a-concourse2-630322659.eu-west-1.elb.amazonaws.com//builds/$BUILD_ID
        The application is now available in Prod - $BUILD_JOB_NAME

- name: create-metrics-forwarder-prod
  public: true
  serial: true
  plan:
  - get: tools
  - get: release
    trigger: true
  - task: build
    file: tools/scripts/create-services.yml
    params:
      <<: *common-params

common-params: &common-params
  APP_NAME: ((app-name))
  CF_USERNAME: ((cf-username))
  CF_API: ((cf-api))
  CF_ORG: ((cf-org))
  CF_PASSWORD: ((cf-password))
