---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: springcloud/pipeline-base 

inputs:
- name: tools 
- name: repo
outputs:
- name: build 

run:
  path: tools/scripts/build.sh 
